# Generated by Django 3.2.3 on 2021-06-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
