# Generated by Django 3.2.3 on 2021-06-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
